version: "3.8"
services:
  rvc:
    shm_size: '8gb'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rvc
    volumes:
      - ./weights:/app/assets/weights
      - ./opt:/app/opt
      - ./dataset:/app/dataset # you can use this folder in order to provide your dataset for model training
      - ./input_audio:/app/input_audio
      - ./output_audio:/app/output_audio
    ports:
      - 7865:7865
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]